### ISSUE TITLE
Does not sync / add cards

### ISSUE THREAD

**Issue by mjak96** [9dogs/notion-anki-sync#3]
Hi,
I have not been able to get it to work. When I open the plugin with Anki I get this:

"Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-05-13 18:19:36
Add-ons possibly involved: ⁨Notion Toggles Loader⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 53, in handler
  File "aqt/main.py", line 143, in on_window_init
  File "aqt/hooks_gen.py", line 1860, in __call__
  File "/Users/martinjakobsson/Library/Application Support/Anki2/addons21/1940767534/__init__.py", line 154, in seed_collection
    self.notes_manager = NotesManager(
  File "/Users/martinjakobsson/Library/Application Support/Anki2/addons21/1940767534/notes_manager.py", line 55, in __init__
    self.create_models()
  File "/Users/martinjakobsson/Library/Application Support/Anki2/addons21/1940767534/notes_manager.py", line 100, in create_models
    cloze_model = model_manager.copy(std_cloze_model)
  File "anki/models.py", line 279, in copy
TypeError: 'NoneType' object is not subscriptable"

**Comment by 9dogs** [comment]
Thanks for reporting! Can you check if a note type `Cloze` is present among your note types? You can check it in the `Tools -> Manage Note Types` list.

**Comment by mjak96** [comment]
This is how it looks for me:
https://ibb.co/YtRHr1n

**Comment by 9dogs** [comment]
I see... I thought `Cloze` type is built-in and unremovable, which is apparently not true. As a workaround, you can try to add a new cloze type with the name "Cloze" (`Add -> Add: Cloze`, name it "Cloze").

**Comment by mjak96** [comment]
Solved it! 
Remember: Some people will use Anki in another language than English and this will rename the Cloze card type to another name. You should implement a check for this.
